### ISSUE TITLE
[Request] Support for CarryOn mod

### ISSUE THREAD

**Issue by vpontin** [Xalcon/ChocoCraft3#15]
Hi!

Can you add please support for [CarryOn](https://minecraft.curseforge.com/projects/carry-on) mod?

This is a amazing mod which lets the player to literally grab any entity (or block with TE).

Sadly i cant grab any chocobo.

Thanks in advance!

**Comment by Tschipp** [comment]
I think this can be closed, this is probably due to config options

**Comment by Xalcon** [comment]
Thanks for the headsup. I didnt check the mod yet, but i dont think i would need to do anything special either.

Also, Chocobos are pretty big, being able to carry them doesnt sound right. If a mod allows you to do this, be my guest. I wont add any special support in chococraft though :P i'd like to keep dependencies to a minimum.

**Comment by vpontin** [comment]
In fact, i think this is all about config, like @Tschipp said.
About the size, the mod is configurable in this part, so if we can we could even carry a horse!

**Comment by Xalcon** [comment]
Well, then I guess this problem is solved. /closed
