### ISSUE TITLE
licences

### ISSUE THREAD

**Issue by ArnoSaxena** [Xalcon/ChocoCraft3#7]
Hi Xalcon, Clienthax contacted me regarding licensing. Looks like you're not very easy to be contacted via gitHub, so I'm writing you an issue ;). Could you contact me at al-s(at)gmx.de?
I had taken over the mod from EddieV and maintained and created most of the stuff currently in it. 
https://github.com/ArnoSaxena/chococraft

Regards :)
  Arno

**Comment by Xalcon** [comment]
You got mail :)
